account_name: "adamoyoung"
project_name: "massformer"
run_name:
data:
  primary_dset: ["nist"]
  secondary_dset: ["mb_na"]
  ce_key: "nce"
  inst_type: ["FT"]
  frag_mode: ["HCD"]
  fp_types: ["morgan","maccs","rdkit"]
  preproc_ce: "normalize"
  spectrum_normalization: "l1"
model:
  embed_types: ["fp"]
  ff_layer_type: "neims"
  ff_h_dim: 2000
  ff_num_layers: 5
  ff_skip: True
  dropout: 0.1
  output_normalization: "l1"
run:
  do_test: True
  do_matching_2: True
  lr: 0.01
  batch_size: 1024
  weight_decay: 0.001
  cuda_deterministic: False
  train_seed: 5585