run_name:
data:
  num_entries: -1
  primary_dset: ["nist"]
  secondary_dset: ["mb_na"]
  ce_key: "nce"
  inst_type: ["FT"]
  frag_mode: ["HCD"]
  pos_prec_type: ['[M+H]+']
  fp_types:   ["morgan","rdkit","maccs"]
  preproc_ce: "normalize"
  spectrum_normalization: "l1"
  casmi_num_entries: -1
  pcasmi_num_entries: -1
model:
  embed_types: ["fp"]
  output_normalization: "l1"
  model_seed: 6666
  cfm_model: True
  cfm_rb: True
run:
  loss: "cos"
  sim: "cos"
  lr: 0.01
  batch_size: 1024
  weight_decay: 0.001
  num_epochs: 0
  num_workers: 4
  cuda_deterministic: False
  do_test: True
  do_matching: False
  do_matching_2: False
  do_casmi: False
  do_pcasmi: False
  save_state: True
  save_media: True
  casmi_save_sim: True
  casmi_batch_size: 100
  casmi_num_workers: 4
  casmi_pred_all: True
  pcasmi_pred_all: False
  log_pcasmi_um: True
  log_auxiliary: True
  train_seed: 5585
  split_seed: 420
  split_key: "scaffold"
  log_tqdm: False
  test_sets: ["train","val","mb_na"]
  save_test_sims: True
  test_frac: 0.