run_name:
data:
  num_entries: -1
  primary_dset: ["nist"]
  secondary_dset: ["mb_na"]
  ce_key: "nce"
  inst_type: ["FT"]
  frag_mode: ["HCD"]
  pos_prec_type: ['[M+H]+', '[M+H-H2O]+', '[M+H-2H2O]+', '[M+2H]2+', '[M+H-NH3]+', "[M+Na]+"]
  fp_types:   ["morgan","rdkit","maccs"]
  preproc_ce: "normalize"
  spectrum_normalization: "l1"
model:
  embed_types: ["fp"]
  output_normalization: "l1"
  model_seed: 6666
  cfm_model: True
  cfm_rb: True
run:
  loss: "cos"
  sim: "cos"
  lr: 0.01
  batch_size: 1024
  weight_decay: 0.001
  num_epochs: 0
  num_workers: 0
  cuda_deterministic: False
  do_test: True
  do_casmi: False
  do_pcasmi: False
  do_casmi22: False
  save_state: True
  save_media: True
  log_auxiliary: True
  train_seed: 5585
  split_seed: 420
  split_key: "scaffold"
  log_tqdm: False
  test_sets: ["train","val","mb_na"]
  save_test_sims: True
  test_frac: 0.
  device: "cpu"
  parallel_strategy: "fs"