run_name:
data:
  num_entries: -1
  primary_dset: ["nist"]
  secondary_dset: ["mb_na"]
  ce_key: "nce"
  inst_type: ["FT"]
  frag_mode: ["HCD"]
  pos_prec_type: ['[M+H]+', '[M+H-H2O]+', '[M+H-2H2O]+', '[M+2H]2+', '[M+H-NH3]+', "[M+Na]+"]
  fp_types:   ["morgan","rdkit","maccs"]
  preproc_ce: "normalize"
  spectrum_normalization: "l1"
  casmi_num_entries: -1
  pcasmi_num_entries: -1
model:
  embed_types: ["wln"]
  gnn_num_layers: 3
  gnn_h_dim: 400
  gnn_pool_type: "max"
  ff_layer_type: "neims"
  ff_h_dim: 1000
  ff_num_layers: 2
  ff_skip: False
  dropout: 0.4
  output_normalization: "l1"
  bidirectional_prediction: True
  model_seed: 6666
run:
  loss: "cos"
  sim: "cos"
  lr: 0.001
  batch_size: 1024
  weight_decay: 0.001
  num_epochs: 100
  num_workers: 10
  cuda_deterministic: False
  do_test: True
  do_matching: False
  do_matching_2: False
  do_casmi: False
  do_pcasmi: False
  save_state: True
  save_media: True
  casmi_save_sim: True
  casmi_batch_size: 400
  casmi_num_workers: 10
  casmi_pred_all: True
  pcasmi_pred_all: False
  log_pcasmi_um: True
  log_auxiliary: True
  train_seed: 5585
  split_seed: 420
  split_key: "scaffold"
  log_tqdm: False
  test_sets: ["train","val","mb_na"]
  save_test_sims: True
  test_frac: 0.