run_name:
data:
  num_entries: -1
  primary_dset: ["nist"]
  secondary_dset: []
  ce_key: "nce"
  inst_type: ["FT"]
  frag_mode: ["HCD"]
  pos_prec_type: ['[M+H]+', '[M+H-H2O]+', '[M+H-2H2O]+', '[M+2H]2+', '[M+H-NH3]+', "[M+Na]+"]
  fp_types:   ["morgan","rdkit","maccs"]
  preproc_ce: "normalize"
  spectrum_normalization: "l1"
  casmi_num_entries: -1
  pcasmi_num_entries: -1
  casmi22_num_entries: -1
  casmi_fp: True
model:
  embed_types: ["fp"]
  ff_layer_type: "neims"
  ff_h_dim: 2000
  ff_num_layers: 5
  ff_skip: True
  dropout: 0.1
  output_normalization: "l1"
  bidirectional_prediction: True
  model_seed: 6666
run:
  loss: "cos"
  sim: "cos"
  lr: 0.01
  batch_size: 1024
  weight_decay: 0.001
  num_epochs: 100
  num_workers: 8
  cuda_deterministic: False
  do_test: True
  do_casmi: True
  do_pcasmi: True
  do_casmi22: True
  save_state: True
  save_media: False
  casmi_save_sim: True
  casmi_batch_size: 512
  casmi_num_workers: 8
  casmi_pred_all: False
  pcasmi_pred_all: False
  casmi22_pred_all: False
  log_pcasmi_um: True
  log_auxiliary: True
  train_seed: 5585
  split_seed: 420
  split_key: "inchikey_s"
  log_tqdm: False
  test_sets: ["train","val"]
  save_test_sims: True
  test_frac: 0.